    save_best: True
    plot_agents: False

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./a2c_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 4
      n_envs: 8
      n_steps: 20
      eval_interval: 2000
      nb_evals: 10
      max_grad_norm: 0.5
      gae: 0.8
      max_epochs: 50000
      discount_factor: 0.95
      entropy_coef: 2.5e-3
      critic_coef: 0.6
      a2c_coef: 1
      actor_type: ConstantVarianceContinuousActor
      architecture:
        actor_hidden_size: [64, 64]
        critic_hidden_size: [64, 64]

    gym_env:
      classname: __main__.make_rl_gym_env
      env_name: RocketLander-v0

    optimizer:
      classname: torch.optim.Adam
      lr: 0.001
