    save_best: True
    plot_agents: True


    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./a2c_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 3
      n_envs: 8
      n_steps: 20
      eval_interval: 2000
      nb_evals: 10
      max_grad_norm: 0.5
      gae: 0.8
      max_epochs: 3000
      discount_factor: 0.99
      entropy_coef: 2.55e-4
      critic_coef: 0.5
      a2c_coef: 1
      actor_type: ConstantVarianceContinuousActor
      architecture:
        actor_hidden_size: [25, 25]
        critic_hidden_size: [25, 25]

    gym_env:
      classname: __main__.make_gym_env
      env_name: CartPoleContinuous-v1

    optimizer:
      classname: torch.optim.Adam
      lr: 0.001
