    save_best: True
    plot_agents: True

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./ddpg_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 1
      nb_seeds: 1
      max_grad_norm: 0.5
      n_envs: 8
      n_steps: 100
      batch_size: 10
      tau_target: 0.8
      eval_interval: 1000
      nb_evals: 10
      gae: 0.8
      max_epochs: 2500
      discount_factor: 0.95
      architecture:
        actor_hidden_size: [64, 64]
        critic_hidden_size: [256, 256]

    gym_env:
      classname: __main__.make_gym_env
      env_name: Pendulum-v1

    optimizer:
      classname: torch.optim.Adam
      lr: 2.3e-3
