      save_best: True
      plot_agents: True

      logger:
            classname: bbrl.utils.logger.TFLogger
            log_dir: ./td3_logs/
            verbose: False
            every_n_seconds: 10

      algorithm:
            seed: 1
            nb_seeds: 1
            n_envs: 1
            n_steps: 100
            max_grad_norm: 0.5
            buffer_size: 2e5
            batch_size: 64
            eval_interval: 2000
            nb_evals: 10
            learning_starts: 10000
            tau_target: 0.05
            action_noise: 0.1
            max_epochs: 5000
            discount_factor: 0.98
            architecture:
                  actor_hidden_size: [256, 256]
                  critic_hidden_size: [256, 256]

      gym_env:
            classname: __main__.make_gym_env
            env_name: CartPoleContinuous-v1

      actor_optimizer:
            classname: torch.optim.Adam
            lr: 1e-4

      critic_optimizer:
            classname: torch.optim.Adam
            lr: 1e-3
