    save_best: False
    plot_agents: False

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./dqn_full_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 4
      nb_seeds: 10
      epsilon_init: 0.02
      epsilon_end: 0.0001
      buffer_size: 1e5
      max_grad_norm: 0.5
      n_envs: 1
      n_steps: 100
      batch_size: 64
      eval_interval: 2000
      start_step: 1000
      target_critic_update: 10000
      nb_evals: 10
      gae: 0.8
      max_epochs: 2500
      discount_factor: 0.99
      architecture:
        hidden_size: [256, 256]

    gym_env:
      classname: __main__.make_gym_env
      env_name: CartPole-v1

    optimizer:
      classname: torch.optim.Adam
      lr: 2.3e-3
