    save_best: True
    plot_agents: True

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./reinforce_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 4
      n_envs: 8
      nb_episodes: 1000
      nb_evals: 10
      discount_factor: 0.95
      entropy_coef: 1
      critic_coef: 1
      actor_coef: 1
      gae: 0.8
      architecture:
        actor_hidden_size: [25, 25]
        critic_hidden_size: [24, 36]

    gym_env:
      classname: __main__.make_gym_env
      env_name: CartPole-v1

    optimizer:
      classname: torch.optim.Adam
      lr: 0.001
