    save_best: True
    plot_agents: True

    logger:
      classname: bbrl.utils.logger.TFLogger
      log_dir: ./ddpg_logs/
      verbose: False
      every_n_seconds: 10

    algorithm:
      seed: 1
      nb_seeds: 1
      max_grad_norm: 0.5
      n_envs: 1
      n_steps: 100
      eval_interval: 2000
      nb_evals: 10
      gae: 0.8
      action_noise: 0.1
      max_epochs: 21000
      discount_factor: 0.98
      entropy_coef: 2.55e-5
      critic_coef: 0.6
      policy_coef: 1
      clip_range: 0.2
      clip_range_vf: 0
      architecture:
        actor_hidden_size: [400, 300]
        critic_hidden_size: [400, 300]

    gym_env:
      classname: __main__.make_gym_env
      env_name: Pendulum-v1

    actor_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3

    critic_optimizer:
      classname: torch.optim.Adam
      lr: 1e-3