      save_best: True
      plot_agents: True

      logger:
            classname: bbrl.utils.logger.TFLogger
            log_dir: ./ppo_logs/
            verbose: False
            every_n_seconds: 10

      algorithm:
            seed: 1
            nb_seeds: 1
            max_grad_norm: 0.5
            n_envs: 8
            n_steps: 100
            eval_interval: 2000
            nb_evals: 3
            gae: 0.95
            max_epochs: 21000
            discount_factor: 0.9
            clip_range: 0.2
            clip_range_vf: 0
            critic_coef: 0.8
            actor_coef: 0.1
            entropy_coef: 0.2
            minibatch_size: 64
            opt_epochs: 50
            beta: 0.5
            architecture:
                  actor_hidden_size: [64, 64]
                  critic_hidden_size: [64, 64]

      gym_env:
            classname: __main__.make_gym_env
            env_name: Pendulum-v1

      optimizer:
            classname: torch.optim.Adam
            lr: 0.002