      save_best: True
      plot_agents: True


      logger:
            classname: bbrl.utils.logger.TFLogger
            log_dir: ./sac_logs/
            verbose: False
            every_n_seconds: 10

      algorithm:
            seed: 5
            n_envs: 8
            n_steps: 100
            eval_interval: 1000
            buffer_size: 2e5
            batch_size: 64
            learning_starts: 10000
            nb_evals: 10
            tau_target: 0.05
            max_epochs: 50000
            max_grad_norm: 0.5
            discount_factor: 0.95
            entropy_coef: 0.1
            target_entropy: auto
            architecture:
                  actor_hidden_size: [256, 256]
                  critic_hidden_size: [256, 256]

      gym_env:
            classname: __main__.make_gym_env
            env_name: Pendulum-v1

      actor_optimizer:
            classname: torch.optim.Adam
            lr: 1e-3

      critic_optimizer:
            classname: torch.optim.Adam
            lr: 1e-3

      entropy_optimizer:
            classname: torch.optim.Adam
            lr: 1e-3

      entropy_coef_optimizer:
            classname: torch.optim.Adam
            lr: 1e-3